contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - busybox
    - ca-certificates-bundle
    - glibc-locale-posix
    - tzdata
    - wolfi-baselayout

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      shell: /bin/sh
  run-as: nonroot

environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
  TZ: Asia/Taipei

paths:
  - path: /etc/distribution/
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o750
  - path: /var/lib/registry/
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o750

archs:
- x86_64
- aarch64
