name: CLIProxyAPI Image CI
permissions: {}

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/CLIProxyAPI.yml'
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/cliproxyapi
  # renovate: datasource=github-releases depName=CLIProxyAPI packageName=router-for-me/CLIProxyAPI
  CLIPROXYAPI_VERSION: v7.2.90

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          repository: 'router-for-me/CLIProxyAPI'
          ref: "${{ env.CLIPROXYAPI_VERSION }}"

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: pre-start
        shell: bash
        run: |
          curl() { $(type -P curl) -LRq --retry 5 --retry-delay 10 --retry-max-time 60 --fail "$@"; }
          curl -o '/tmp/.ko.yaml' -- \
              https://raw.githubusercontent.com/IceCodeNew/docker-collections/master/.cliproxyapi.ko.yaml

      - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10
        env:
          KO_DOCKER_REPO: docker.io/${{ env.REGISTRY_IMAGE }}
      - run: ko build --platform=linux/amd64,linux/arm64 --bare ./cmd/server/
        env:
          KO_CONFIG_PATH: /tmp/.ko.yaml
