name: CLIProxyAPI Image CI
permissions: {}

on:
  push:
    branches:
    - 'release'
    paths:
    - '.github/workflows/CLIProxyAPI.yml'
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/cliproxyapi
  CLIPROXYAPI_VERSION: v7.0.4

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          repository: 'router-for-me/CLIProxyAPI'
          ref: "${{ env.CLIPROXYAPI_VERSION }}"

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: pre-start
        shell: bash
        run: |
          curl() { $(type -P curl) -LRq --retry 5 --retry-delay 10 --retry-max-time 60 --fail "$@"; }
          curl -o '/tmp/.ko.yaml' -- \
              https://raw.githubusercontent.com/IceCodeNew/docker-collections/master/.cliproxyapi.ko.yaml

      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9
        env:
          KO_DOCKER_REPO: docker.io/${{ env.REGISTRY_IMAGE }}
      - run: ko build --platform=linux/amd64,linux/arm64 --bare ./cmd/server/
        env:
          KO_CONFIG_PATH: /tmp/.ko.yaml
