name: gg Image CI
permissions: {}

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/gg.yml'
  schedule:
  - cron: "0 4 1 * *"
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          repository: 'IceCodeNew/gg'

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: pre-start
        shell: bash
        run: |
          curl() { $(type -P curl) -LRq --retry 5 --retry-delay 10 --retry-max-time 60 --fail "$@"; }
          curl -o '/tmp/.ko.yaml' -- \
              https://raw.githubusercontent.com/IceCodeNew/docker-collections/master/default.ko.yaml

      - uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9
        env:
          KO_DOCKER_REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/gg
      - run: ko build --platform=linux/amd64,linux/arm64 --bare .
        env:
          KO_CONFIG_PATH: /tmp/.ko.yaml
