name: mmp-go Image CI
permissions: {}

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/mmp-go.yml'
  schedule:
  - cron: "0 4 1 * *"
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          repository: 'IceCodeNew/mmp-go'

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Set some variables
        shell: bash
        run: |
          VERSION=$(git describe --exact-match HEAD 2>/dev/null || git describe --tags --always)
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"

      - uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9
        env:
          KO_DOCKER_REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/mmp-go
      - run: ko build --platform=linux/amd64,linux/arm64 --bare .
