name: mmp-go Image CI
permissions: {}

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/mmp-go.yml'
  schedule:
  - cron: "0 4 1 * *"
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          repository: 'IceCodeNew/mmp-go'

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Set some variables
        shell: bash
        run: |
          VERSION=$(git describe --exact-match HEAD 2>/dev/null || git describe --tags --always)
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"

      - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10
        env:
          KO_DOCKER_REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/mmp-go
      - run: ko build --platform=linux/amd64,linux/arm64 --bare .
